name: user_recipeapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.10.1
  supabase_flutter: ^2.8.3
  image_picker: ^1.1.2
  intl: ^0.20.2
  path: ^1.9.0
  dropdown_search: ^6.0.2
  search_choices: ^2.3.1
  share_plus: ^10.1.4
  google_fonts: ^6.2.1
  fl_chart: ^0.70.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/